import random
jokes = [
  'What do you call a bear with no teeth? A gummy bear!',
  'What do you call a fake noodle? An impasta!',
  'What do you call a cow with two legs? Lean beef!',
  'Why couldn’t the bicycle stand up by itself? It was two tired!',
  'How does a penguin build it’s house? Igloos it together!',
  'What do you call an alligator in a vest? An investigator!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
  'What do you call a fat psychic? A four-chin teller!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
  'What do you call a fat psychic? A four-chin teller!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
  'What do you call a fat psychic? A four-chin teller!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
  'What do you call a fat psychic? A four-chin teller!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
  'What do you call a fat psychic? A four-chin teller!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
  'What do you call a fat psychic? A four-chin teller!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
  'What do you call a fat psychic? A four-chin teller!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
  'What do you call a fat psychic? A four-chin teller!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
  'What do you call a fat psychic? A four-chin teller!',
  'What do you call a belt made out of watches? A waist of time!',
  'Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent!',
  'What do you call cheese that isn’t yours? Nacho cheese!',
  'What kind of shoes do ninjas wear? Sneakers!',
  'What do you call a dog that does magic tricks? A labracadabrador!',
]

pick  = jokes[random.randint(0, len(jokes)-1)]
print('Q: ' + pick.split('? ')[0] + '?')
print('A: ' + pick.split('?')[1].strip())
